using System;
using System.IO;
using System.Linq;

namespace WindowsAuditTool.Services;

/// <summary>
/// Finds the HTML audit report generated by Run-Audit.ps1.
/// </summary>
public static class ReportLocator
{
    /// <summary>
    /// Finds the most recent audit HTML report.
    /// Checks: 1) the explicit path captured from script output,
    /// 2) the Results subfolder next to the exe, 3) the Windows Audit Tool subfolder.
    /// </summary>
    public static string? FindReport(string? capturedPath = null)
    {
        // If the script told us the exact path, use it
        if (!string.IsNullOrEmpty(capturedPath) && File.Exists(capturedPath))
            return capturedPath;

        // Search common output locations
        var baseDir = AppContext.BaseDirectory;
        string[] searchDirs =
        [
            Path.Combine(baseDir, "Windows Audit Tool"),
            Path.Combine(baseDir, "Results"),
            baseDir,
            @"C:\Program Files\Windows Audit Tool\Results"
        ];

        foreach (var dir in searchDirs)
        {
            if (!Directory.Exists(dir))
                continue;

            var latest = Directory.GetFiles(dir, "*-Audit.html")
                .Select(f => new FileInfo(f))
                .OrderByDescending(f => f.LastWriteTimeUtc)
                .FirstOrDefault();

            if (latest != null)
                return latest.FullName;
        }

        return null;
    }
}
